---
- name: Créer un répertoire, un groupe, un utilisateur et définir les permissions
  hosts: all
  become: yes  # Exécuter les tâches avec des privilèges élevés
  tasks:
    - name: Créer un répertoire
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      loop: "{{ rep }}"

    - name: Créer un groupe d'utilisateurs
      ansible.builtin.group:
        name: app_group
        state: present

    - name: Créer un utilisateur et l'ajouter au groupe
      ansible.builtin.user:
        name: "{{ item }}"
        group: app_group
        create_home: yes
        state: present
      loop: "{{ user }}"

    - name: Appliquer les droits de l'utilisateur et les permissions sur le répertoire
      ansible.builtin.file:
        path: "{{ item }}"
        owner: app_user
        group: app_group
        mode: '0744'  # Permissions 744 pour le répertoire
      loop: "{{ rep }}"
